---
- name: Converge
  hosts: cassandra
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure correct java version is selected
      alternatives:
        link: /usr/bin/java
        name: java
        path: /opt/java/jdk8u242/bin/java
        priority: 1

  vars:
    role_path: "{{ lookup('env', 'ROLE_PATH') }}"

  roles:
    - name: "{{ role_path if role_path is defined and role_path else lookup('env', 'HOME') + '/ansible-role-cassandra' }}"
